begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values
 ('11000000-0000-0000-0000-000000000001','portal-owner@example.test',now(),'{"full_name":"Solicitante"}'),
 ('11000000-0000-0000-0000-000000000002','portal-admin@example.test',now(),'{"full_name":"Admin"}'),
 ('11000000-0000-0000-0000-000000000003','portal-worker@example.test',now(),'{"full_name":"Trabajador"}'),
 ('11000000-0000-0000-0000-000000000004','portal-other@example.test',now(),'{"full_name":"Otro ciudadano","role":"platform_admin"}');
insert into platform_admins(user_id) values('11000000-0000-0000-0000-000000000002');
insert into storage.objects(bucket_id,name) values('company-documents','11000000-0000-0000-0000-000000000001/test.pdf');
set local role anon;
select throws_ok($$select portal_command('submit_application','{}')$$,'42501',null,'guest cannot submit or execute commands');
select throws_ok($$select * from company_applications$$,'42501',null,'guest cannot read applications');
select is((select count(*) from storage.objects where bucket_id='company-documents'),0::bigint,'guest cannot read documents');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','11000000-0000-0000-0000-000000000001',true);
select lives_ok($$select portal_command('submit_application','{"businessName":"Portal test company","legalName":"Test SA","taxId":"20123456789","corporateEmail":"portal-owner@example.test","phone":"12345678","responsible":"Solicitante","address":"Calle 123","activity":"Reciclaje","documentPath":"11000000-0000-0000-0000-000000000001/test.pdf"}')$$,'applicant submits documented application');
select is((select count(*) from company_applications where applicant_id=auth.uid()),1::bigint,'own application is readable');
select is((select count(*) from companies where name='Portal test company'),0::bigint,'submission does not activate company');
select throws_ok($$select portal_command('review_application',jsonb_build_object('id',(select id from company_applications where applicant_id=auth.uid()),'status','APPROVED'))$$,'42501',null,'applicant cannot self-approve');
select throws_ok($$insert into company_applications(applicant_id) values(auth.uid())$$,'42501',null,'direct client inserts cannot forge status');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','11000000-0000-0000-0000-000000000004',true);
select is((select count(*) from company_applications),0::bigint,'other citizen cannot read private application');
select is((select count(*) from storage.objects where bucket_id='company-documents'),0::bigint,'other citizen cannot read private document');
select throws_ok($$select portal_command('save_global_xp','{"categories":[]}')$$,'42501',null,'user_metadata cannot authorize admin changes');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','11000000-0000-0000-0000-000000000002',true);
select lives_ok($$select portal_command('review_application',jsonb_build_object('id',(select id from company_applications where tax_id='20123456789'),'status','NEEDS_INFO','note','Adjuntar una aclaración'))$$,'admin requests information');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','11000000-0000-0000-0000-000000000001',true);
select lives_ok($$select portal_command('resubmit_application',jsonb_build_object('id',(select id from company_applications where applicant_id=auth.uid()),'businessName','Portal test company','legalName','Test SA','taxId','20123456789','corporateEmail','portal-owner@example.test','phone','12345678','responsible','Solicitante','address','Calle 123','activity','Reciclaje','documentPath','11000000-0000-0000-0000-000000000001/test.pdf'))$$,'applicant resubmits requested information');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','11000000-0000-0000-0000-000000000002',true);
select lives_ok($$select portal_command('review_application',jsonb_build_object('id',(select id from company_applications where tax_id='20123456789'),'status','APPROVED'))$$,'admin approves atomically');
select lives_ok($$select portal_command('review_application',jsonb_build_object('id',(select id from company_applications where tax_id='20123456789'),'status','APPROVED'))$$,'approval is idempotent');
select is((select count(*) from companies where name='Portal test company'),1::bigint,'repeat approval creates one company');
select is((select count(*) from company_invitations where email='portal-owner@example.test'),1::bigint,'one owner invitation');
select lives_ok($$select invitation_recipient((select id from company_invitations where email='portal-owner@example.test'))$$,'admin can send pending owner invitation');
select throws_ok($$select invitation_recipient((select id from company_invitations where email='portal-owner@example.test'))$$,'22023',null,'email resend is throttled');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','11000000-0000-0000-0000-000000000001',true);
select lives_ok($$select portal_command('accept_invitation',jsonb_build_object('id',(select id from company_invitations where email='portal-owner@example.test')))$$,'verified owner accepts invitation');
select lives_ok($$select portal_command('accept_invitation',jsonb_build_object('id',(select id from company_invitations where email='portal-owner@example.test')))$$,'invitation acceptance is idempotent');
select ok(private.has_company_role((select company_id from company_memberships where user_id=auth.uid()),true),'owner receives active company access');
select lives_ok($$select portal_command('save_point',jsonb_build_object('companyId',(select company_id from company_memberships where user_id=auth.uid()),'name','Punto de prueba','address','Calle 123','latitude',-34.6,'longitude',-58.4,'timeZone','America/Argentina/Buenos_Aires','active',true,'pickupEnabled',true,'categories',jsonb_build_array((select id from device_categories where slug='celulares')),'schedules','[{"weekday":1,"opensMinute":540,"closesMinute":1080}]'::jsonb))$$,'owner publishes point with categories and schedule atomically');
select lives_ok($$select portal_command('save_points',jsonb_build_object('companyId',(select company_id from company_memberships where user_id=auth.uid()),'categories',jsonb_build_array(jsonb_build_object('id',(select id from device_categories where slug='celulares'),'points',80))))$$,'owner sets company points');
select lives_ok($$select portal_command('invite_worker',jsonb_build_object('companyId',(select company_id from company_memberships where user_id=auth.uid()),'email','portal-worker@example.test'))$$,'owner invites worker');
select throws_ok($$select portal_command('set_company_status',jsonb_build_object('id',(select company_id from company_memberships where user_id=auth.uid()),'status','SUSPENDED','note','Intento'))$$,'42501',null,'owner cannot suspend company');
reset role;
-- Test one reserved slot. Owner not counted toward worker limit.
update companies set worker_limit=1 where name='Portal test company';
set local role authenticated;
select set_config('request.jwt.claim.sub','11000000-0000-0000-0000-000000000001',true);
select throws_ok($$select portal_command('invite_worker',jsonb_build_object('companyId',(select company_id from company_memberships where user_id=auth.uid()),'email','portal-other@example.test'))$$,'22023',null,'pending invitation reserves last worker slot');
select lives_ok($$select portal_command('request_limit',jsonb_build_object('companyId',(select company_id from company_memberships where user_id=auth.uid()),'limit',10,'reason','Necesitamos incorporar más trabajadores.'))$$,'owner requests higher limit');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','11000000-0000-0000-0000-000000000003',true);
select lives_ok($$select portal_command('accept_invitation',jsonb_build_object('id',(select id from company_invitations where email='portal-worker@example.test')))$$,'worker accepts reserved slot');
select throws_ok($$select portal_command('save_company',jsonb_build_object('companyId',(select company_id from company_memberships where user_id=auth.uid()),'name','Attack','address','Fake','phone','123'))$$,'42501',null,'worker cannot edit company');
select throws_ok($$select portal_command('invite_worker',jsonb_build_object('companyId',(select company_id from company_memberships where user_id=auth.uid()),'email','attack@example.test'))$$,'42501',null,'worker cannot invite team');
select is((select count(*) from company_details),0::bigint,'worker cannot read legal data');
select is((select count(*) from audit_log),0::bigint,'worker cannot read audit');
reset role;
set local role anon;
select is((select count(*) from green_points where name='Punto de prueba'),1::bigint,'published point visible to citizens');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','11000000-0000-0000-0000-000000000002',true);
select lives_ok($$select portal_command('review_limit',jsonb_build_object('id',(select id from company_limit_requests where reason='Necesitamos incorporar más trabajadores.'),'status','APPROVED'))$$,'admin approves worker limit');
select is((select worker_limit from companies where name='Portal test company'),10,'approved limit applied');
select lives_ok($$select portal_command('save_global_xp',jsonb_build_object('categories',jsonb_build_array(jsonb_build_object('id',(select id from device_categories where slug='celulares'),'xp',15))))$$,'admin changes XP globally');
select throws_ok($$select portal_command('save_level',jsonb_build_object('id',(select id from impact_levels where minimum_xp=0),'name','Semilla','minimumXp',10))$$,'22023',null,'initial level retains zero threshold in backend');
select lives_ok($$select portal_command('set_company_status',jsonb_build_object('id',(select id from companies where name='Portal test company'),'status','SUSPENDED','note','Revisión administrativa'))$$,'admin suspends company');
select ok((select count(*) from audit_log)>10,'actions audited');
reset role;
set local role anon;
select is((select count(*) from green_points where name='Punto de prueba'),0::bigint,'suspended company point hidden immediately');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','11000000-0000-0000-0000-000000000001',true);
select throws_ok($$select portal_command('save_points',jsonb_build_object('companyId',(select company_id from company_memberships where user_id=auth.uid()),'categories','[]'::jsonb))$$,'42501',null,'suspended company cannot operate');
reset role;
select * from finish();
rollback;
